# Generated by Django 4.2.7 on 2026-01-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                ("duration_hours", models.DecimalField(decimal_places=1, max_digits=3)),
                ("credits_amount", models.IntegerField()),
                ("location_details", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("teacher_confirmed", models.BooleanField(default=False)),
                ("learner_confirmed", models.BooleanField(default=False)),
                ("proposed_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges_as_learner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="skills.skilloffer",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exchanges",
                "ordering": ["-proposed_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "status"],
                        name="exchanges_teacher_f95289_idx",
                    ),
                    models.Index(
                        fields=["learner", "status"],
                        name="exchanges_learner_16391e_idx",
                    ),
                ],
            },
        ),
    ]
