# Generated by Django 4.2.27 on 2026-01-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='skills.skilloffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Application',
                'verbose_name_plural': 'Skill Applications',
                'db_table': 'skill_applications',
                'unique_together': {('user', 'skill_offer')},
            },
        ),
    ]
