# Generated by Django 4.2.27 on 2026-01-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skillapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Dynamic logo URL for the category', max_length=500, null=True),
        ),
    ]
