# Generated by Django 4.2.7 on 2026-01-07 00:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="exchanges.exchange",
            ),
        ),
    ]
